[package]
name = "svelte-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clone-macro = "0.1"
js-sys = "0.3"
log = "0.4"
wasm-bindgen = "0.2"